import express from "express";
import cors from "cors";
import pinoHttp from "pino-http";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { existsSync } from "fs";
import router from "./routes/index.js";
import { logger } from "./lib/logger.js";
import { db, productsTable, categoriesTable } from "./db/index.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const app = express();
const port = Number(process.env.PORT ?? 3000);
const isProduction = process.env.NODE_ENV === "production";

app.use(
  pinoHttp({
    logger,
    serializers: {
      req(req) { return { id: req.id, method: req.method, url: req.url?.split("?")[0] }; },
      res(res) { return { statusCode: res.statusCode }; },
    },
  }),
);

app.use(cors({ origin: true, credentials: true }));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

app.use("/api", router);

if (isProduction) {
  const publicDir = join(__dirname, "public");
  if (existsSync(publicDir)) {
    app.use(express.static(publicDir));
    app.get("/{*path}", (_req, res) => {
      res.sendFile(join(publicDir, "index.html"));
    });
  }
}

async function seedDatabase() {
  const existing = await db.select().from(productsTable).limit(1);
  if (existing.length > 0) return;

  logger.info("Sembrando catálogo inicial en SQLite...");

  await db.insert(categoriesTable).values([
    { name: "Cadenas", slug: "cadenas", description: "Cadenas de oro y plata de alta calidad" },
    { name: "Pulseras", slug: "pulseras", description: "Pulseras para todas las ocasiones" },
    { name: "Anillos", slug: "anillos", description: "Anillos de lujo y compromiso" },
    { name: "Aretes", slug: "aretes", description: "Aretes elegantes y exclusivos" },
    { name: "Collares", slug: "collares", description: "Collares únicos y lujosos" },
    { name: "Relojes", slug: "relojes", description: "Relojes de lujo y precisión" },
  ]);

  await db.insert(productsTable).values([
    {
      name: "Pulsera Eslabón Cubano ",
      description: "El clásico diseño Unisex cubano llevado al siguiente nivel de brillo. Esta pulsera de plata italiana cuenta con eslabones meticulosamente pavimentados con circonias de alta calidad y un broche de seguridad tipo cajón, una pieza imponente y con mucho estilo.",
      price: 535000,
      originalPrice: 600000,
      category: "pulseras",
      subcategory: "plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1780113134/708536706_17870740644677507_5806512027029785331_n_qz7n9b.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 40,
      material: "Plata Italiana 9.25 ",
      weight: "",
      collection: "ICONIC OF ROWGOLD",
      rating: 5.0,
      reviewCount: 45,
    },
    
    {
      name: "Collar de Tréboles Verdes",
      description: "Este diseño clásico intercala tréboles de cuatro hojas verdes",
      price: 143000,
      originalPrice: null,
      category: "collares",
      subcategory: "oro blanco",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1780028172/707308402_17870738712677507_2338569982685114741_n_uyj1ze.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 50,
      material: "Plata Italiana 925",
      weight: "28g",
      collection: "ICONIC OF ROWGOLD",
      rating: 5.0,
      reviewCount: 24,
    },
      {
      name: "Pulsera Mariposa",
      description: "Pulsera para Dama con un hermoso dije central de mariposa, incluye cadena ajustable para adaptarse perfectamente a cualquier muñeca.",
      price: 55000,
      originalPrice: null,
      category: "pulseras",
      subcategory: "plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1780093941/52A737CB-571C-4DC0-B211-45990B43A0E5_ppbyzx.jpg",
      featured: true,
      instock: true,
      stockQuantity: 50,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 4.7,
      reviewCount: 22,
    },
     {
      name: "Anillo Halo Corazón",
      description: "Anillo en Plata Italiana 925, con piedra en corazon verde, con color  rosado, verde, azul.",
      price: 115000,
      originalPrice: null,
      category: "anillo",
      subcategory: "plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1783825092/WhatsApp_Image_2026-07-11_at_9.34.15_PM_sipjgz.jpg",
      featured: true,
      instock: true,
      stockQuantity: 70,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 4.7,
      reviewCount: 22,
    },
     
    {
      name: "Pulsera Rope Chain",
      description: "Pulsera clásica de cadena de cuerda Unisex en plata Italiana 925. Su diseño entrelazado captura la luz desde cualquier ángulo, aportando un brillo elegante",
      price: 80000,
      originalPrice: 100000,
      category: "pulseras",
      subcategory: "oro",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1780093898/099FD742-D45A-4665-86B3-D62B19C23860_xfqbzy.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 70,
      material: "Oro 18K",
      weight: "",
      collection: "",
      rating: 5.0,
      reviewCount: 27,
    },
    {
      name: "Pulsera Eslabón Diamantada",
      description: "Pulsera Diamantada para caballero en plata Italiana 925 con un diseño moderno, plano y con mucha personalidad para destacar tu estilo.",
      price: 140000,
      originalPrice: 155000,
      category: "pulseras",
      subcategory: "plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1780093922/78C47220-BDFB-42AC-A3E5-60A51E39AD5D_mcr1hr.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 70,
      material: "Plata Italiana 9.25",
      weight: "12g",
      collection: "ROWGOLD",
      rating: 4.9,
      reviewCount: 41,
    },
    {
      name: "Cadena Bismark",
      description: "Diseño Unisex. Esta pulsera combina eslabones Cartier labrados en plata italiana con detalles en resina negra brillante, creando un contraste imponente y sofisticado.",
      price: 290000,
      originalPrice: null,
      category: "cadenas",
      subcategory: "compromiso",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1780130299/IMG_3904_kxk6ka.jpg",
      images: ["https://res.cloudinary.com/dmlpiqian/image/upload/v1780130299/IMG_3904_kxk6ka.jpg"],
      featured: true,
      inStock: true,
      stockQuantity: 70,
      material: "Oro Laminado 18k",
      weight: "5g",
      collection: "ICONIC OF ROWGOLD",
      rating: 5.0,
      reviewCount: 63,
    },
    {
      name: "Anillo Meditation Ring",
      description: "Anillo eternidad con rubíes naturales y diamantes alternados en oro amarillo 18K. Símbolo de amor eterno y pasión.",
      price: 180000,
      originalPrice: null,
      category: "anillos",
      subcategory: "gemas",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1780123973/IMG_3894_wmlead.jpg",
      images: ["https://res.cloudinary.com/dmlpiqian/image/upload/v1780123973/IMG_3894_wmlead.jpg"],
      featured: false,
      inStock: true,
      stockQuantity: 76,
      material: "Oro Laminado 18K",
      weight: "7g",
      collection: "ICONIC OF ROWGOLD",
      rating: 4.8,
      reviewCount: 19,
    },
    {
      name: "Aretes Perlas Akoya",
      description: "Aretes de perlas Akoya japonesas 7-7.5mm en montura de oro blanco 18K. Brillo excepcional, lustre satinado natural.",
      price: 680,
      originalPrice: 820,
      category: "aretes",
      subcategory: "perlas",
      imageUrl: "https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=600&auto=format&fit=crop",
      images: ["https://images.unsplash.com/photo-1601121141461-9d6647bef0a1?w=600&auto=format&fit=crop"],
      featured: false,
      inStock: true,
      stockQuantity: 72,
      material: "Perla Akoya + Oro 18K",
      weight: "4g",
      collection: "Elegancia",
      rating: 4.7,
      reviewCount: 33,
    },
    {
      name: "Pulsera de Trébol",
      description: "Esta Pulsera Unisex se destaca por sus icónicos Tréboles con sutiles verde y bordes texturizados. Una pieza en tendencia ideal para realzar cualquier look..",
      price: 125000,
      originalPrice: null,
      category: "pulseras",
      subcategory: "plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1780128463/IMG_3905_svcnrf.jpg",
       images: ["https://res.cloudinary.com/dmlpiqian/image/upload/v1782513219/IMG_5125_ahsgyo.jpg"], 
       images: ["https://res.cloudinary.com/dmlpiqian/image/upload/v1782513187/IMG_5124_wplss4.jpg "],
      featured: true,
      inStock: true,
      stockQuantity: 70,
      material: "Plata Italiana 9.25",
      weight: "6g",
      collection: "ROWGOLD",
      rating: 4.9,
      reviewCount: 24,
    },
    
    {
      name: "Pulsera Eslabón Slim",
      description: "Esta tobillera en Plata 925 destaca por su icónico tejido de eslabón marino y diseñado para asentarse con total comodidad y destellar con elegancia en cada paso.",
      price: 70000,
      originalPrice: 95000,
      category: "pulseras",
      subcategory: "plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1780130201/IMG_3906_a5b8gu.jpg",
      images: ["https://res.cloudinary.com/dmlpiqian/image/upload/v1780130201/IMG_3906_a5b8gu.jpg"],
      featured: false,
      inStock: true,
      stockQuantity: 70,
      material: "Plata Italiana 9.25",
      weight: "65g",
      collection: "Exclusiva",
      rating: 5.0,
      reviewCount: 32,
    },
    {
      name: "Cadena Rope Chain",
      description: "Tejido de cuerda que refleja luz con cada movimiento y se ve gruesa sin ser pesada.",
      price: 178000,
      originalPrice: null,
      category: "cadenas",
      subcategory: "Plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1780124207/IMG_3886_dajndo.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 70,
      material: "Plata Italiana 9.25",
      weight: "8g",
      collection: "ICONIC OF ROWGOLD",
      rating: 4.8,
      reviewCount: 45,
    },
    {
      name: "Pulsera Cuban Link",
      description: "Pulsera en plata 9.25 para hombre. Eslabones planos y macizos que le dan presencia y brillo sin exagerar, cuenta con un design urbano",
      price: 115000,
      originalPrice: null,
      category: "pulseras",
      subcategory: "Plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1780094003/ED7BB661-6079-4D76-B822-08A31FB72EC3_lzsvik.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 78,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 5.0,
      reviewCount: 27,
    },
    {
      name: "Pulsera Grumet Slim",
      description: "Pulsera Grumet delgada en Oro Laminado 18K, tejido plano que se adapta a la muñeca con un brillo en cada movimiento",
      price: 275000,
      originalPrice: null,
      category: "pulseras",
      subcategory: "Oro",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782341578/IMG_4949_xrqkfb.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 78,
      material: "Oro Laminado 18k",
      weight: "",
      collection: "ROWGOLD",
      rating: 5.0,
      reviewCount: 25,
    },
    {
      name: "Anillo V-Star",
      description: "La estrella y  la V. Dos anillos para dama con un solo look en Plata italiana, delicado, brillante y diferente a lo tipico",
      price: 85000,
      originalPrice: null,
      category: "anillos",
      subcategory: "Plata 925",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782341785/IMG_4945_t7zwy3.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 78,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 5.0,
      reviewCount: 30,
    },
    {
      name: "Candongas Doble",
      description: "Candongas tipo Argolla texturizada. Este detalle les da brillo sin necesidad de piedras, y las hace ver menos lisas/planas",
      price: 160000,
      originalPrice: null,
      category: "aretes",
      subcategory: "Plata 925",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782341796/IMG_4950_ngb5hw.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 78,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 5.0,
      reviewCount: 27,
    },
    {
      name: "Anillo Glaciar",
      description: "Anillo Unisex en Plata Italiana 9.25 perfecto para apilar con otros anillos, con un brillo y un detalle trenzado que lo hace diferente",
      price: 98000,
      originalPrice: null,
      category: "anillos",
      subcategory: "Plata 925",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782341805/IMG_4946_xeb1ic.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 78,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 5.0,
      reviewCount: 47,
    },
    {
      name: "Cadena Milan ",
      description: "Cadena Milan en Oro Laminado de 18k, con eslabones aplanados con  mayor brillo y caida. Diseño unisex, resistentes y sin enredos",
      price: 350000,
      originalPrice: null,
      category: "cadenas",
      subcategory: "Oro",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782341814/IMG_4948_p7lj5t.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 78,
      material: "Oro Laminado 18k",
      weight: "",
      collection: "ROWGOLD",
      rating: 5.0,
      reviewCount: 27,
    },
    {
      name: "Pulsera Esclava Unisex ",
      description: "Pulsera Esclava en plata 925, comoda para uso diario y con cierre seguro. La placa permite marcar el Nombre, fechas o iniciales",
      price: 155000,
      originalPrice: 170000,
      category: "pulseras",
      subcategory: "Plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782356541/IMG_5006_1_afyqbt.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 78,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ICONIC OF ROWGOLD",
      rating: 5.0,
      reviewCount: 38,
    },
    {
      name: "Pulsera Figaro",
      description: "Pulsera Figaro con eslabones aplanados que reflejan la luz y dan brillo en Oro Laminado",
      price: 120000,
      originalPrice: null,
      category: "pulseras",
      subcategory: "Oro",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782355349/IMG_4998_sxnkb2.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 78,
      material: "Oro Laminado 18k",
      weight: "",
      collection: "ROWGOLD",
      rating: 5.0,
      reviewCount: 43,
    },
    {
      name: "Aretes Colibri",
      description: "Aretes en Plata 925 con forma de colibri en vuelo. Cuerpo en circonis verde y alas pave  con brillo, y sutiles femeninos",
      price: 48000,
      originalPrice: null,
      category: "aretes",
      subcategory: "Plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782355361/IMG_4999_iodwc7.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 78,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 4.8,
      reviewCount: 26,
    },
    {
      name: "Anillo Aurora Rose",
      description: "Anillo Aurora Rouse, una piedra rectangular tono rosa en plata italiana, cuenta con un diseño fino y romantico, perfecto para uso diario o  una ocasión",
      price: 110000,
      originalPrice: null,
      category: "anillos",
      subcategory: "Plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782355373/IMG_5001_t6ehqx.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 78,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 4.9,
      reviewCount: 61,
    },
    {
      name: "Candongas Duo",
      description: "Candongas tipo huggie en plata 925, cierre seguro, brillantes y elegantes para uso diario",
      price: 110000,
      originalPrice: null,
      category: "aretes",
      subcategory: "Plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782355386/IMG_5002_ushg9u.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 78,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 4.9,
      reviewCount: 31,
    },
    {
      name: "Cadena Figaro Milan",
      description: "Cadena tejido figaro con eslabones planos que reflejan la luz. Versatil, resistente y atemporal, uso de cadena sola o con Dije para darle personalidad.",
      price: 145000,
      originalPrice: null,
      category: "cadenas",
      subcategory: "Plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1780125877/IMG_3892_cheup8.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 78,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 4.9,
      reviewCount: 58,
    },
    {
      name: "Anillo Eternity",
      description: "Anillo en Plata italiana 9.25 y Oro Laminado 18k unisex. Diseño de nudo celta trenzado en el centro, simboliza la eternidad, conexion infinita y union sin principio ni fin.",
      price: 180000,
      originalPrice: null,
      category: "anillos",
      subcategory: "Oro",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782367809/IMG_5041_xvjin6.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 78,
      material: "Oro Plata",
      weight: "",
      collection: "ICONIC OF ROWGOLD",
      rating: 4.9,
      reviewCount: 63,
    },
    {
      name: "Topos De Cruz",
      description: "Topos de Cruz, en plata 925 con piedras fijas y delicados para uso diario",
      price: 46000,
      originalPrice: null,
      category: "aretes",
      subcategory: "Plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782849476/IMG_5328_xzqxay.jpg",
      featured: true,
      inStock: true,
      stockQuantity: 58,
      material: "Plata Italiana 9.25",
      codigo:"RG-ARE-001",
      weight: "",
      collection: "ROWGOLD",
      rating: 4.9,
      reviewCount: 58,
    },
    {
      name: "Aretes Ruby",
      description: "Aretes en Oro Laminado 18k, con circonia corte redondo color zafiro azul y rojo profundo, elegantes y atemporales",
      price: 80000,
      originalPrice: null,
      category: "aretes",
      subcategory: "Oro",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782367766/IMG_5036_fx8tzv.jpg",
      images: ["https://res.cloudinary.com/dmlpiqian/image/upload/v1782367734/IMG_5035_lljikn.jpg"], 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "Oro Laminado 18k",
      weight: "",
      collection: "ROWGOLD",
      rating: 4.9,
      reviewCount: 46,
    },
    {
      name: "Cofre De Osito Nieve",
      description: "Cofre organizador en forma de Osito acabado mate blanco, sostiene esfera transparente. Dentro guarda el anillo de compromiso.",
      price: 120000,
      originalPrice: null,
      category: "accesorios",
      subcategory: "Oro",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782367778/IMG_5031_umzwz5.jpg",
      images: [
        "https://res.cloudinary.com/dmlpiqian/image/upload/v1782367755/IMG_5033_gw83az.jpg",
        "https://res.cloudinary.com/dmlpiqian/image/upload/v1782367712/IMG_5032_e7hymx.jpg"
      ], 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "",
      weight: "",
      collection: "ROWGOLD",
      rating: 4.9,
      reviewCount: 33,
    },
    {
      name: "Anillo de Corazón",
      description: "Anillo de corazon en plata italiana 925. Delicado, femenino y de tu estilo",
      price: 95000,
      originalPrice: null,
      category: "anillos",
      subcategory: "plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782367745/IMG_5037_btgn6n.jpg", 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 4.8,
      reviewCount: 36,
    },
    {
      name: "Cadena Singapur",
      description: "Acabado diamantado que refleja la luz con cada movimiento, liviana y flexible que eleva con cualquier Outfit",
      price: 85000,
      originalPrice: null,
      category: "cadenas",
      subcategory: "plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782367704/IMG_5034_q98owu.jpg", 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 5.0,
      reviewCount: 57,
    },
    {
      name: "Pulsera Milan II",
      description: "Tejido pulido que refleja la luz, diseño atemporal para caballero resistente y flexible",
      price: 148000,
      originalPrice: null,
      category: "pulseras",
      subcategory: "plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782367724/IMG_5039_kpug5z.jpg", 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 5.0,
      reviewCount: 69,
    },
    {
      name: "Cadena Singapur II",
      description: "Cadena para Dama en Oro Laminado 18k. Se reconoce por sus eslabones en espiral que giran sobre si mismo.",
      price: 136000,
      originalPrice: null,
      category: "cadenas",
      subcategory: "Oro",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782408124/IMG_5051_i7yjrs.jpg", 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "Oro Laminado 18k",
      weight: "",
      collection: "ROWGOLD",
      rating: 4.7,
      reviewCount: 35,
    },
    {
      name: "Cadena Tokyo",
      description: "Cadena Tokyo en Plata Italiana 9.25 para caballero, tejido doble curb en acabado pulido, doble hilera con eslabones planos entrelazados que crea superficie ancha, ",
      price: 255000,
      originalPrice: 286000,
      category: "cadenas",
      subcategory: "plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782402198/IMG_5014_rx5ydr.jpg", 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 5.0,
      reviewCount: 36,
    },
    {
      name: "Anillo Band Liso",
      description: " Anillo Band Liso unisex en Plata 925, diseño atemporal, elegante y comodo para uso diario ",
      price: 145000,
      originalPrice: null,
      category: "anillos",
      subcategory: "plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782402235/IMG_5015_s2znlj.jpg", 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 5.0,
      reviewCount: 46,
    },
    {
      name: "Cadena Paperclip",
      description: "Cadena paperclip en baño de Oro 18k con acabado pulido. Esta cadena cuenta con un diseño geometrico, plano y con mucho movimiento",
      price: 265000,
      originalPrice: null,
      category: "cadenas",
      subcategory: "Oro",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782408113/IMG_5052_ekh3kg.jpg", 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "Oro Laminado de 18k",
      weight: "",
      collection: "ROWGOLD",
      rating: 5.0,
      reviewCount: 30,
    },
    {
      name: "Pulsera Essential ",
      description: "Pulsera Essential con eslabones entrelazados, que quedan rectos en la muñeca, es un diseño unisex atemporal.",
      price: 160000,
      originalPrice: null,
      category: "pulseras",
      subcategory: "Plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782402227/IMG_5040_dvciio.jpg", 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 4.8,
      reviewCount: 43,
    },
    {
      name: "Cadena Marina",
      description: "Esta Cadena es inspirada en anclas marinas diseño con movmiento, textura y peso, un clasico moderno unisex en Plata Italiana 9.25",
      price: 685000,
      originalPrice: null,
      category: "cadenas",
      subcategory: "Plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782402190/IMG_5016_ttybrb.jpg", 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 4.8,
      reviewCount: 14,
    },
       {
      name: "Aretes Cisnes",
      description: "Aretes tipo topos en baño de Oro 18K. Las alas y cuerpo llevan circonias verdes, post fijo con mariposa para seguridad, ideales para uso diario o regalo",
      price: 75000,
      originalPrice: null,
      category: "aretes",
      subcategory: "oro",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782428730/IMG_5079_gn77ku.jpg", 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "Oro Laminado 18K",
      weight: "",
      collection: "ROWGOLD",
      rating: 4.9,
      reviewCount: 33,
    },
    
     {
      name: "Pulsera Figaro Roma",
      description: "Pulsera Unisex tejido figaro acabado pulido en plata 9.25, el diseño plano queda recto en la muñeca, refleja luz en todo lado.",
      price: 115000 ,
      originalPrice: null,
      category: "pulseras",
      subcategory: "Plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782428942/IMG_5065_bn2imq.jpg", 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 4.8,
      reviewCount: 8,
    },
     {
      name: "Pulsera Sleek ",
      description: "Pulsera Unisex con un tejido serpiente pulido, fabricada con placas metálicas entrelazadas que forman una cinta lisa, flexible y continua, se adapta perfecto a la muñeca sin marcar y refleja luz en toda su superficie,",
      price: 296000,
      originalPrice: 320000,
      category: "pulseras",
      subcategory: "Plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782428749/IMG_5066_t8zurb.jpg", 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ICONIC OF ROWGOLD",
      rating: 4.9,
      reviewCount: 9,
    },
    {
      name: "Dije Virgen Milagrosa",
      description: "Dije circular en baño de oro 18K con figura de la Virgen Milagrosa al centro en alto relieve, diseño doble: espiritual por la medalla y lujoso por el pavé. Tamaño mediano perfecto para uso diario. ",
      price:  88000,
      originalPrice: null,
      category: "accesorios",
      subcategory: "Oro",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782428905/IMG_5085_nvp7b9.jpg", 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "Oro Laminado 18k",
      weight: "",
      collection: "ICONIC OF ROWGOLD ",
      rating: 4.9,
      reviewCount: 10,
    },
     {
      name: "Cadena Figaro Roma",
      description: "Cadena tejido Figaro con un acabado pulido, el eslabón plano refleja luz desde todos los ángulos, es atemporal y unisex",
      price: 168000 ,
      originalPrice: null,
      category: "cadenas",
      subcategory: "Plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782428933/IMG_5080_n0o3ny.jpg", 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 4.8,
      reviewCount: 31,
    },
    {
      name: "Pulsera Mariner",
      description: "Pulsera para caballero con tejido mariner en plata 925 con acabado pulido y borde pavé de circonias.",
      price: 265000 ,
      originalPrice: null,
      category: "pulseras",
      subcategory: "Plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782432210/IMG_5067_datugl.jpg", 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ROWGOLD",
      rating: 4.8,
      reviewCount: 14,
    },
    {
      name: "Collar Eternity Green",
      description: "Collar Eternity Green, diseño continuo que se adapta al cuello, en Plata Italiana 9.25",
      price: 820000 ,
      originalPrice: null,
      category: "collares",
      subcategory: "Plata",
      imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782367821/IMG_5043_tjt6ew.jpg", 
      featured: true,
      inStock: true,
      stockQuantity: 98,
      material: "Plata Italiana 9.25",
      weight: "",
      collection: "ICONIC OF ROWGOLD",
      rating: 5.0,
      reviewCount: 5,
    },
   {

name: "Anillo Hamsa Protector",
description: " Anillo circular en plata 9.25 con corona en el centro con detalles árabes",
price: 155000,
originalPrice: null,
category: "anillos",
subcategory: "Plata ",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782437993/IMG_5095_r8yqjr.jpg",
featured: true,
instock: true,
stockQuantity: 98,
material: "Plata Italiana 9.25",
weight: "",
collection: "ROWGOLD",
rating: 4.8,
reviewCount:36,

},
{

name: "Anillos Royal Crest ",
description: " Nueva Edición de ROWGOLD en Plata Premium para mayor brillo y resistencia a la oxidación, manteniendo la coherencia del lenguaje visual de la pieza en Plata Italiana 9.25",
price: 175000,
originalPrice: null,
category: "anillos",
subcategory: "Plata",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782438005/IMG_5096_n4jqp2.jpg",
featured: true,
instock: true,
stockQuantity: 98,
material: "Plata Italiana 9.25",
weight: "",
collection: "ROWGOLD",
rating: 5.0,
reviewCount: 48,

},
{

name: "Anillo Royal Emblem ",
description: " Colección ROWGOLD, elaborada en base de Plata 9.25 Con símbolo de corona con textura martillada, genera contraste y profundidad, enmarcando el emblema central.",
price: 290000,
originalPrice: null,
category: "anillos",
subcategory: "Plata",
imageUrl:" https://res.cloudinary.com/dmlpiqian/image/upload/v1782438022/IMG_5097_e7bgv8.jpg",
featured: true,
instock: true,
stockQuantity: 98,
material: "Plata Italiana 9.25",
weight: "",
collection: "ICONIC OF ROWGOLD",
rating: 5.0,
reviewCount: 42,
},
{

name: "Anillos Square",
description: " Eslabón geométrico que aporta ritmo, técnica y un guiño a la relojería clásica, es una joya para hombre contemporáneo en Plata Italiana 9.25",
price: 290000,
originalPrice: null,
category: "anillos",
subcategory: "Plata ",
imageUrl: " https://res.cloudinary.com/dmlpiqian/image/upload/v1782439866/IMG_5099_n40qcw.jpg",
featured: true,
instock: true,
stockQuantity: 98,
material: "Plata Italiana 9.25",
weight: "",
collection: "ROWGOLD",
rating: 4.8,
reviewCount:36,

},
  {
name: "Pulsera De Órbita y Esferas",
description: "Pulsera para Dama de línea contemporánea elaborada en Plata 9.25 con acabado pulido de alto brillo",
price: 155000,
originalPrice: null,
category: "pulsera",
subcategory: "Plata ",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782428737/IMG_5086_w3t9ce.jpg",
featured: true,
instock: true,
stockQuantity: 98,
material: "Plata Italiana 9.25",
weight: "",
collection: "ICONIC OF ROWGOLD",
rating: 4.8,
reviewCount: 35,

},
    {
name: "Anillo Carmesí",
description: "Anillo Carmesí para Dama en Plata Italiana 9.25, el diseño se centra en una piedra roja de corte brillante que permite el paso máximo de luz y realza su color profundo",
price: 110000,
originalPrice: null,
category: "anillos",
subcategory: "Plata ",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782442970/IMG_5100_un6s78.jpg",
featured: true,
instock: true,
stockQuantity: 98,
material: "Plata Italiana 9.25",
weight: "",
collection: "ROWGOLD",
rating: 4.8,
reviewCount: 39,
},
{

name: "Pulsera Prisma",
description: "Pulsera para Dama de línea contemporánea elaborada en Plata 9.25 con acabado pulido de alto brillo",
price: 128000,
originalPrice: null,
category: "pulsera",
subcategory: "Plata ",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782429044/IMG_5089_xbq4ok.jpg",
featured: true,
instock: true,
stockQuantity: 98,
material: "Plata Italiana 9.25",
weight: "",
collection: "ROWGOLD",
rating: 4.8,
reviewCount:56,

},
 {

name: "Cadena Aurelia Mesh",
description: "Cadena tipo malla plana elaborada con tejido Italiano cerrado, y acabajo en baño de oro de 18K. Es una pieza atemporal, ancha y con presencia Unisex.",
price: 595000,
originalPrice: null,
category: "cadenas",
subcategory: "Oro",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782429135/IMG_5090_vgk5gz_xlzqem.jpg",
featured: true,
instock: true,
stockQuantity: 98,
material: "Oro Laminado 18k",
weight: "",
collection: "ROWGOLD",
rating: 5.0,
reviewCount:16,
},
  {

name: "Dije  Royal Crest",
description: "Dije unisex circular de line a premium elaborado een baño de Oro, el diseño se centra en una corona en alto relieve, simbolo universal de liderazgo, logro y autoestima.",
price: 130000,
originalPrice: null,
category: "accessorios",
subcategory: "Oro",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782428949/IMG_5088_mpg0ud.jpg",
featured: true,
instock: true,
stockQuantity: 98,
material: "Oro Laminado 18k",
weight: "",
collection: "ROWGOLD",
rating: 4.8,
reviewCount: 28,

},
     {

name: "Pulsera Magica",
description: "Pulsera Hongo Magico para dama, elaborado en plata Italiana 9.25 graduable para un Look ligero y moderno ",
price: 88000,
originalPrice: null,
category: "pulseras",
subcategory: "plata",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782522135/IMG_5145_e0egsr_tw6kzz.jpg",
featured: true,
instock: true,
stockQuantity: 98,
material: "Plata Italiana 9.25",
weight: "",
collection: "ROWGOLD",
rating: 4.9,
reviewCount:56,
     }, 
  { 
name: "Pulsera Triplo Mesh",
description: "Pulsera para caballero, con tejido cerrado elaborada en Plata Italiana 925 con acabado pulido y esoejo de alto brillo, este diseño crea una pieza ancha y flexible que cae perfectamente en la muñeca",
price: 155000,
originalPrice: null,
category: "pulseras",
subcategory: "plata",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782521954/IMG_5060_sfs7jz.jpg",
featured: true,
instock: true,
stockQuantity: 98,
material: "Plata Italiana 9.25",
weight: "",
collection: "ROWGOLD",
rating: 5.0,
reviewCount: 56,

},
{
name: "Pulsera Ruby Beetle", 
description: "Pulsera delicada para dama en Plata Italiana 925. Este diseño se centra en un dije de mariquita delicada. La mariquita es un simbolo universal de buena suerte, proteccion y nuevos comienzos. ",
price: 95000,
originalPrice: null,
category: "pulsera",
subcategory: "Plata ",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782523423/IMG_5147_jzryvk.jpg",
featured: true,
instock: true,
stockQuantity: 98,
material: "Plata Italiana 9.25",
weight: "",
collection: "ICONIC OF ROWGOLD",
rating: 4.8,
reviewCount: 43,

},
   {
name: "Pulsera Sweet Cherry", 
description: "Este diseño se centra en un Dije de cereza dobles en esmaltte rojo brillantecon hoja verde, esta pulsera en plata italian 9.25 para dama simboliza juventud, amor y dulzura ",
price: 88000,
originalPrice: null,
category: "pulsera",
subcategory: "Plata ",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782574210/IMG_5165_m0gxld.jpg",
featured: true,
instock: true,
stockQuantity: 98,
material: "Plata Italiana 9.25",
weight: "",
collection: "ROWGOLD",
rating: 4.9,
reviewCount: 78,

},
  {
name: "Pulsera Watermelon", 
description: " Summer Slice es una pulsera en Plata 925, es el accesorio perfecto para regalo y para  quienes aman los detalles unicos ",
price: 86000,
originalPrice: null,
category: "pulsera",
subcategory: "Plata ",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782574209/IMG_5164_y9pvuf.jpg ",
featured: true,
instock: true,
stockQuantity: 8,
material: "Plata Italiana 9.25",
weight: "",
collection: "ROWGOLD",
rating: 5.0,
reviewCount: 48,

},
    {
name: "Pulsera Lumiére", 
description: "Pulsera de diseño orbital elaborada en Plata 925 con acabado pulido espejo de alto brillo. Inspirada en el movimiento del sistema solar, su composición se basa en equilibrio gravitacional. Esferas pulidas representan cuerpos celestes, gotas alargadas simulan cometas en trayectoria y el dije flor calado funciona como estrella central o constelación. Las cuentas corazón son puntos de luz, estrellas que orbitan. ",
price: 135000,
originalPrice: null,
category: "pulsera",
subcategory: "Plata ",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782574222/IMG_5166_sf0kta.jpg",
featured: true,
instock: true,
stockQuantity: 8,
material: "Plata Italiana 9.25",
weight: "",
collection: "ICONIC OF ROWGOLD",
rating: 5.0,
reviewCount: 28,

},
  {
name: "Cadena de Eslabón en Esferas", 
description: "Diseñada para quienes aprecian la sofisticación sin esfuerzo, esta cadena de esferas en Oro Laminado fusiona un ícono de la joyería clásica con una estética moderna y completamente unisex. ",
price: 220000,
originalPrice: null,
category: "cadenas",
subcategory: "Oro",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782603982/IMG_5192_zfcxdc.jpg",
featured: true,
instock: true,
stockQuantity: 8,
material: "Oro Lamindado 18k",
weight: "",
collection: "ROWGOLD",
rating: 5.0,
reviewCount:16,

},
      {
name: "Candongas Ovaladas", 
description: "Estas candongas ovaladas en oro laminado fusionan un diseño vanguardista de líneas limpias con un sutil detalle frontal en pavé de brillos. ",
price: 85000,
originalPrice: null,
category: "aretes",
subcategory: "plata",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782603271/IMG_5182_fithvo.jpg",
featured: true,
instock: true,
stockQuantity: 8,
material: "Plata Italiana 9.25",
weight: "",
collection: "ROWGOLD",
rating: 5.0,
reviewCount: 23,

},
{
name: "Cadena Fígaro V", 
description: "Un clásico italiano reinterpretado en clave minimalista. Esta cadena con el icónico tejido Fígaro combina tres eslabones circulares y uno alargado en una silueta delgada de alta sofisticación. Su diseño atemporal y estilizado posee un enfoque estrictamente unisex, ideal para quienes buscan un accesorio ligero de uso diario.",
price: 230000,
originalPrice: null,
category: "cadenas",
subcategory: "Oro",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782604712/IMG_5194_vc1xvu.jpg",
featured: true,
instock: true,
stockQuantity: 8,
material: "Oro Laminado 18k",
weight: "",
collection: "ROWGOLD",
rating: 4.9,
reviewCount: 33,

},
    {
name: "Topos Corazón", 
description: "Topos para dama elaborados en Plata Ley 925 rinden homenaje a la elegancia clásica con un diseño cautivador. La pieza es protagonizada por una gema central en color verde  con un impecable corte en forma de corazón, abrazada por un delicado halo de circonias premium engastadas que maximizan su brillo y profundidad. ",
price: 75000,
originalPrice: null,
category: "aretes",
subcategory: "plata",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782603982/IMG_5191_jilx1g.jpg",
featured: true,
instock: true,
stockQuantity: 8,
material: "Plata Italiana 9.25",
weight: "",
collection: "ROWGOLD",
rating: 4.9,
reviewCount: 36,

},
{
name: "Candongas Con Grabado Diamantado", 
description: "Estas candongas circulares en Plata Ley 925 combinan el balance perfecto que destacan por su delicado grabado diamantado sobre el metal, un labrado de alta precisión que captura los reflejos lumínicos de manera única y sofisticada. ",
price: 120000,
originalPrice: null,
category: "aretes",
subcategory: "plata",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782603272/IMG_5183_fjxkgd.jpg",
featured: true,
instock: true,
stockQuantity: 8,
material: "Plata Italiana 9.25",
weight: "",
collection: "ROWGOLD",
rating: 4.9,
reviewCount: 36,

},
    {
name: "Topos Unisex", 
description: " ",
price: 43000,
originalPrice: null,
category: "aretes",
subcategory: "plata",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782611490/IMG_5196_x6eloe.jpg",
 images: ["https://res.cloudinary.com/dmlpiqian/image/upload/v1782611490/IMG_5197_jacpwh.jpg"],
featured: true,
instock: true,
stockQuantity: 8,
material: "Plata Italiana 9.25",
weight: "",
collection: "ROWGOLD",
rating: 5.0,
reviewCount: 38,

},
     {
name: "Serene Heart", 
description: "Plata pura. Azul magnético. Corazones que inspiran. Descubre una joya diseñada para perdurar, donde el romance de sus formas se encuentra con el lujo de los detalles. Un tributo a la feminidad y al brillo auténtico. ",
price: 570000,
originalPrice: null,
category: "pulsera",
subcategory: "plata",
imageUrl: "https://res.cloudinary.com/dmlpiqian/image/upload/v1782367802/IMG_5042_cnbzce.jpg",
featured: true,
instock: true,
stockQuantity: 8,
material: "Plata Italiana 9.25",
weight: "",
collection: "ROWGOLD",
rating: 5.0,
reviewCount: 38,

},
     
  
  ]);

  logger.info("Base de datos sembrada: 12 productos y 6 categorías creados");
}

async function main() {
  try {
    await seedDatabase();
  } catch (err) {
    logger.error({ err }, "Error al sembrar la base de datos");
  }

  app.listen(port, "0.0.0.0", () => {
    logger.info({ port, mode: process.env.NODE_ENV ?? "development" }, "ROWGOLD server listening");
  });
}

main();

export default app;
